name: VapStuffEngine
description: 'TypeScript engine for VapStuff'
version: '1.3.2'
api-version: '1.13'
author: AStorks + Vap0r1ze
main: com.pixlfox.scriptablemc.SMCJavaScriptEngineMain
depend: []
softdepend: [PlaceholderAPI]
