name: ScriptableMC-Engine-PY
description: 'Run Python plugins for Bukkit/Spigot/Paper Minecraft 1.15'
version: '1.3.0'
api-version: '1.13'
author: AStorks
main: com.pixlfox.scriptablemc.SMCPythonEngineMain
depend: []
softdepend: [PlaceholderAPI]