name: Build Dev
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Node.js 12.14.1
      uses: actions/setup-node@v1
      with:
        node-version: 12.14.1
    - name: Fix gradlew permissions
      run: chmod +x ./gradlew
    - name: Export TypeScript Libraries with Gradle
      run: ./gradlew :ScriptableMC-Tools-TS:exportTypeScriptLibraries
    - name: Compile TypeScript libraries and create archives
      run: |
        cd ./ScriptableMC-Tools-TS/lib/
        npm install
        npm run compile
        cd ./ts/
        zip -r ../ScriptableMC-TypeScript-Lib.zip ./*
        cd ../js/
        zip -r ../ScriptableMC-JavaScript-Lib.zip ./*
        cd ../
        cp ./ScriptableMC-JavaScript-Lib.zip ../../ScriptableMC-Engine-JS/src/main/resources/libraries.zip
    - name: Export lib-smc with gradle
      run: ./gradlew :ScriptableMC-Tools-TS:generateLibSMC
    - name: Compile lib-smc, create archive, and publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ./ScriptableMC-Tools-TS/lib-smc/
        npm install
        npm run compile
        npm publish ./js
        zip -r ./Lib-SMC.zip ./*
    - name: Build All Plugins with Gradle
      run: ./gradlew :shadowJarAll
    - name: Copy artifacts
      run: |
        mkdir artifacts
        cp ./build/ScriptableMC-Engine-JS.jar ./artifacts/
        cp ./build/ScriptableMC-Engine-JS-Bundled.jar ./artifacts/
        cp ./ScriptableMC-Tools-TS/lib/ScriptableMC-TypeScript-Lib.zip ./artifacts/
        cp ./ScriptableMC-Tools-TS/lib/ScriptableMC-JavaScript-Lib.zip ./artifacts/
        cp ./ScriptableMC-Tools-TS/lib-smc/Lib-SMC.zip ./artifacts/
    - uses: actions/upload-artifact@v1
      with:
        name: ScriptableMC-Engine-DEV
        path: artifacts/
