name: Build TS Libraries

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Node.js 12.14.1
      uses: actions/setup-node@v1
      with:
        node-version: 12.14.1
    - name: Fix gradlew permissions
      run: chmod +x ./gradlew
    - name: Export TypeScript Libraries with Gradle
      run: ./gradlew :ScriptableMC-Tools-TS:exportTypeScriptLibraries
    - name: Deploy Built Libraries
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: libs
        FOLDER: ScriptableMC-Tools-TS/lib/ts
        CLEAN: true
