name: Build and Upload Release Artifacts
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Node.js 12.14.1
      uses: actions/setup-node@v1
      with:
        node-version: 12.14.1
    - name: Fix gradlew permissions
      run: chmod +x ./gradlew
    - name: Export TypeScript Libraries with Gradle
      run: ./gradlew :ScriptableMC-Tools-TS:exportTypeScriptLibraries
    - name: Compile TypeScript libraries and create archives
      run: |
        cd ./ScriptableMC-Tools-TS/lib/
        npm install
        npm run compile
        cd ./ts/
        zip -r ../ScriptableMC-TypeScript-Lib.zip ./*
        cd ../js/
        zip -r ../ScriptableMC-JavaScript-Lib.zip ./*
        cd ../
        cp ./ScriptableMC-JavaScript-Lib.zip ../../ScriptableMC-Engine-JS/src/main/resources/libraries.zip
    - name: Export lib-smc with gradle
      run: ./gradlew :ScriptableMC-Tools-TS:generateLibSMCRelease
    - name: Compile lib-smc, create archive, and publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        cd ./ScriptableMC-Tools-TS/lib-smc/
        npm install
        npm run compile
        npm publish ./js --access public
        zip -r ./Lib-SMC.zip ./*
    - name: Build JS Engine with Gradle
      run: ./gradlew :shadowJarAll
    - name: Upload JavaScript Engine Plugin Jar
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'ScriptableMC-Engine-JS/build/libs/ScriptableMC-Engine-JS.jar'
    - name: Upload Bundled JavaScript Engine Plugin Jar
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'ScriptableMC-Engine-JS/Bundled/build/libs/ScriptableMC-Engine-JS-Bundled.jar'
    - name: Upload TypeScript Libraries
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'ScriptableMC-Tools-TS/lib/ScriptableMC-TypeScript-Lib.zip'
    - name: Upload JavaScript Libraries
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'ScriptableMC-Tools-TS/lib/ScriptableMC-JavaScript-Lib.zip'
